// © 2023 SolarWinds Worldwide, LLC. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package swo

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"strings"
	"testing"

	"github.com/solarwinds/apm-go/internal/config"
	"github.com/solarwinds/apm-go/internal/entryspans"
	"github.com/solarwinds/apm-go/internal/log"
	"github.com/solarwinds/apm-go/internal/state"
	"github.com/solarwinds/apm-go/internal/testutils"
	"github.com/solarwinds/apm-go/internal/utils"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/sdk/resource"
	"go.opentelemetry.io/otel/sdk/trace"
)

func TestSetGetLogLevel(t *testing.T) {
	oldLevel := GetLogLevel()

	err := SetLogLevel("INVALID")
	assert.Equal(t, err, errInvalidLogLevel)

	nl := "ERROR"
	err = SetLogLevel(nl)
	assert.Nil(t, err)

	newLevel := GetLogLevel()
	assert.Equal(t, newLevel, nl)

	require.NoError(t, SetLogLevel(oldLevel))
}

func TestSetLogOutput(t *testing.T) {
	oldLevel := GetLogLevel()
	_ = SetLogLevel("DEBUG")
	defer func() {
		require.NoError(t, SetLogLevel(oldLevel))
	}()

	var buf utils.SafeBuffer
	SetLogOutput(&buf)
	defer func() {
		SetLogOutput(os.Stderr)
	}()

	log.Info("hello world")
	assert.True(t, strings.Contains(buf.String(), "hello world"))
}

func TestCreateResource(t *testing.T) {
	r, err := createResource(attribute.String("foo", "bar"))
	require.NoError(t, err)
	collected := make(map[string]attribute.KeyValue)
	for _, kv := range r.Attributes() {
		collected[string(kv.Key)] = kv
	}

	require.Equal(t, attribute.String("foo", "bar"), collected["foo"])
	// These are all generated by the Otel SDK, so we check existence but not the value
	require.NotNil(t, collected["os.description"])
	require.NotNil(t, collected["os.type"])
	require.NotNil(t, collected["process.command_args"])
	require.NotNil(t, collected["process.executable.name"])
	require.NotNil(t, collected["process.executable.path"])
	require.NotNil(t, collected["process.owner"])
	require.NotNil(t, collected["process.pid"])
	require.NotNil(t, collected["telemetry.sdk.language"])
	require.NotNil(t, collected["telemetry.sdk.name"])
	require.NotNil(t, collected["telemetry.sdk.version"])
}

func TestSetTransactionName(t *testing.T) {
	err := SetTransactionName(context.Background(), "    ")
	require.Error(t, err)
	require.Equal(t, "invalid transaction name", err.Error())

	err = SetTransactionName(context.Background(), "valid")
	require.Error(t, err)
	require.Equal(t, "could not obtain OpenTelemetry SpanContext from given context", err.Error())

	tr, teardown := testutils.TracerSetup()
	defer teardown()
	ctx, s := tr.Start(context.Background(), "span name")
	err = entryspans.Push(s.(trace.ReadWriteSpan))
	require.NoError(t, err)
	err = SetTransactionName(ctx, "this should work")
	require.NoError(t, err)
	require.Equal(t, "this should work", entryspans.GetTransactionName(s.SpanContext().TraceID()))

}

func TestServiceNameFromResource(t *testing.T) {
	t.Run("returns service.name when present", func(t *testing.T) {
		r := resource.NewSchemaless(attribute.String("service.name", "resource-service-name"))
		assert.Equal(t, "resource-service-name", serviceNameFromResource(r))
	})

	t.Run("returns empty string when service.name absent", func(t *testing.T) {
		r := resource.NewSchemaless(attribute.String("some.other.attr", "value"))
		assert.Equal(t, "", serviceNameFromResource(r))
	})
}

func TestServiceNamePrecedence(t *testing.T) {
	const (
		validKey         = "ae38315f6116585d64d82ec2455aa3ec61e02fee25d286f74ace9e4fea189217:key-service-name"
		disableDetectors = "ec2,azurevm,uams"
	)

	tests := []struct {
		name         string
		envSvcName   string
		resourceAttr string
		want         string
	}{
		{
			name: "service key is baseline",
			want: "key-service-name",
		},
		{
			name:       "OTEL_SERVICE_NAME overrides service key",
			envSvcName: "env-service-name",
			want:       "env-service-name",
		},
		{
			name:         "resourceAttr overrides OTEL_SERVICE_NAME",
			envSvcName:   "env-service-name",
			resourceAttr: "api-service-name",
			want:         "api-service-name",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Cleanup(func() { config.Load() })
			t.Setenv("SW_APM_SERVICE_KEY", validKey)
			t.Setenv("OTEL_SERVICE_NAME", tt.envSvcName)
			t.Setenv("SW_APM_DISABLED_RESOURCE_DETECTORS", disableDetectors)
			config.Load()

			var attrs []attribute.KeyValue
			if tt.resourceAttr != "" {
				attrs = append(attrs, attribute.String("service.name", tt.resourceAttr))
			}
			r, err := createResource(attrs...)
			require.NoError(t, err)
			assert.Equal(t, tt.want, serviceNameFromResource(r))
		})
	}
}

// Regression test for NH-141898: state.SetServiceName lost its call site when AO
// support was removed, causing state.GetServiceName() to always return "".
func TestStartSetsStateServiceName(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(`{"flags":"SAMPLE_START","value":1000000,"ttl":60,"arguments":{"BucketCapacity":1,"BucketRate":1}}`))
	}))
	defer server.Close()

	const token = "ae38315f6116585d64d82ec2455aa3ec61e02fee25d286f74ace9e4fea189217"
	t.Cleanup(func() {
		state.SetServiceName("")
		config.Load()
	})
	t.Setenv("SW_APM_SERVICE_KEY", token+":key-service-name")
	t.Setenv("OTEL_SERVICE_NAME", "env-service-name")
	t.Setenv("OTEL_EXPORTER_OTLP_ENDPOINT", "http://localhost:4317")
	t.Setenv("SW_APM_DISABLED_RESOURCE_DETECTORS", "ec2,azurevm,uams")
	config.Load(func(c *config.Config) { c.SettingsURL = server.URL })

	shutdown, err := Start()
	require.NoError(t, err)
	defer shutdown()

	assert.Equal(t, "env-service-name", state.GetServiceName())
}

func TestStartDisabled(t *testing.T) {
	t.Setenv("SW_APM_ENABLED", "false")
	config.Load()

	cb, err := Start()
	require.NoError(t, err)
	require.NotNil(t, cb)

	// The returned shutdown func must be a no-op (not nil) and must not panic.
	cb()
}
