name: test

on:
  pull_request: null
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  license-check:
    runs-on: ubuntu-latest
    name: License header check
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: ./license_check.sh
  fmt-check:
    runs-on: ubuntu-latest
    name: "`gofmt` check"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: Jerome1337/gofmt-action@d5eabd189843f1d568286a54578159978b7c0fb1 # v1.0.5
  tests:
    strategy:
      matrix:
        goversion: ['1.25', '1.26']
        os: ['ubuntu-latest', 'windows-latest']
    name: Go ${{ matrix.goversion }} (${{ matrix.os}}) tests
    runs-on: ${{ matrix.os }}
    env:
      SW_APM_DEBUG_LEVEL: 1
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.goversion }}
      - name: Install dependencies
        run: |
          go get -t -v ./...
      - name: Go vet
        run: go vet ./...
      - name: Run tests
        run: make test
