name: test

on:
  pull_request: null
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  license-check:
    runs-on: ubuntu-latest
    name: License header check
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: ./license_check.sh
  fmt-check:
    runs-on: ubuntu-latest
    name: "`gofmt` check"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: Jerome1337/gofmt-action@d5eabd189843f1d568286a54578159978b7c0fb1 # v1.0.5
  tests:
    strategy:
      matrix:
        goversion: ['1.25', '1.26']
        os: ['ubuntu-latest', 'windows-latest']
    name: Go ${{ matrix.goversion }} (${{ matrix.os}}) tests
    runs-on: ${{ matrix.os }}
    env:
      SW_APM_DEBUG_LEVEL: 1
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ matrix.goversion }}
      - name: Install dependencies
        run: |
          go get -t -v ./...
      - name: Go vet
        run: go vet ./...
      - name: Run tests
        run: make test
